export const styles = {
    downloadMessage: {
        zIndex: 1,
        position: 'fixed',
        bottom: '20px',
        right: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        color: 'white',
        padding: '10px',
        borderRadius: '5px',
    },
    remainingCharacters: {
        zIndex: 1,
        marginTop: '5px',
        position: 'relative',
        fontSize: '18px',
        textAlign: 'center',
        color: 'white',
        display: 'flex',
        bottom: '35px',
        left: '50%',
        alignItems: 'center',
    },
    deleteButton: {
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        marginLeft: '3%',
        marginRight: '30%',
        padding: '10px',
        borderRadius: '5px',
        cursor: 'pointer',
    },
    textBoxEmail: {
        zIndex: 1,
        position: 'relative',
        left: '10%',
        width: '55%',
        height: '100px',
        paddingBottom: '30px',
        padding: '10px',
        fontSize: '16px',
        backgroundColor: '#000000',
        color: '#ffffff',
        borderRadius: '5px',
        marginBottom: '10%',
    },
    textBox: {
        zIndex: 1,
        position: 'relative',
        left: '10%',
        width: '55%',
        height: '60px',
        paddingBottom: '30px',
        padding: '10px',
        fontSize: '16px',
        backgroundColor: '#000000',
        color: '#ffffff',
        borderRadius: '5px',
        marginBottom: '10%',
    },
    tmdbActionsButton: {
        zIndex: 1,
        position: 'relative',
        marginTop: '20px',
        backgroundColor: '#000000',
        color: '#ffffff',
        paddingHorizontal: 16,
        paddingVertical: 10,
        left: '10%',
        width: '55%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        flex : 1,
        textAlign: 'center',
        marginBottom: '10%',
        cursor: 'pointer',
    },
    weatherActionsButton: {
        zIndex: 1,
        position: 'relative',
        marginTop: '20px',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '10%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '10%',
        cursor: 'pointer',
    },
    cityTextBox: {
        zIndex: 1,
        position: 'relative',
        left: '10%',
        width: '55%',
        height: '60px',
        paddingBottom: '30px',
        padding: '10px',
        fontSize: '16px',
        backgroundColor: '#000000',
        color: '#ffffff',
        borderRadius: '5px',
    },
    timeActionsButton: {
        zIndex: 1,
        position: 'relative',
        marginTop: '20px',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '10%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '10%',
        cursor: 'pointer',
    },
    timeIntervalButton: {
        zIndex: 1,
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '10%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '10%',
        cursor: 'pointer',
    },
    actionContainer: {
        position: 'absolute',
        width: '20%',
        height: '55%',
        top: '28%',
        left: '25%',
        alignSelf: 'center',
        backgroundColor: '#242222',
        borderRadius: '5px',
        overflowX: 'auto',
    },
    handleLoginWithDiscordAction: {
        zIndex: 1,
        position: 'relative',
        marginTop: '20px',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '10%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '10%',
        cursor: 'pointer',
    },
    handleDiscordActionSelected: {
        zIndex: 1,
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '10%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: '10%',
        marginBottom: '10%',
    },
    handleDiscordChannelChangeAction: {
        zIndex: 1,
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '10%',
        padding: 16,
        borderRadius: 2,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '10%',
    },
    handleDiscordServerChangeAction: {
        zIndex: 1,
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '10%',
        padding: 16,
        borderRadius: 2,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '10%',

    },
    handleDiscordUserChangeAction: {
        zIndex: 1,
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '10%',
        padding: 16,
        borderRadius: 2,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '10%',
    },
    handleDiscordMessage: {
        zIndex: 2,
        position: 'relative',
        left: '10%',
        width: '55%',
        height: '60px',
        paddingBottom: '30px',
        padding: '10px',
        fontSize: '16px',
        backgroundColor: '#000000',
        color: '#ffffff',
        borderRadius: '5px',
    },
    recentAppText: {
        position: 'absolute',
        fontSize: '20px',
        left: '30%',
        top: '46%',
        color: '#000000',
    },
    dashboardButton: {
        position: 'absolute',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '5%',
        top: '25%',
        fontSize: '20px',
        fontWeight: 'bold',
        padding: '10px',
        borderRadius: '25px',
        cursor: 'pointer',
    },
    confirmEdit: {
        zIndex: 1,
        position: 'absolute',
        backgroundColor: '#000000',
        color: '#ffffff',
        top: '80%',
        left: '40%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '20%',
    },
    closeEdit: {
        zIndex: 1,
        position: 'absolute',
        backgroundColor: '#000000',
        color: '#ffffff',
        top: '80%',
        left: '60%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '20%',
    },
    editPage: {
        zIndex: 2,
        position: 'absolute',
        width: '65%',
        height: '400px',
        left: '10%',
        border: '1px solid gray',
        borderRadius: '5px',
        backgroundColor: '#EEEEEE',
    },
    reactionContainer: {
      position: 'absolute',
        width: '20%',
        height: '55%',
        top: '28%',
        left: '59.8%',
        backgroundColor: '#242222',
        borderRadius: '5px',
        overflowX: 'auto',
    },
    handleLoginWithDiscord: {
        zIndex: 1,
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '54%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        border: '1px solid gray',
        marginBottom: '10%',
        marginTop: '20px',
    },
    handleDiscordReactionSelected: {
        zIndex: 1,
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '25%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: '10%',
        marginBottom: '10%',
    },
    handleDiscordServerChange: {
        zIndex: 1,
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '31%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '10%',
    },
    handleDiscordChannelChange: {
        zIndex: 1,
        position: 'absolute',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '28%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '10%',
    },
    handleDiscordUserChange: {
        zIndex: 1,
        position: 'relative',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '35%',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    container: {
        padding: '20px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },  button: {
        backgroundColor: '#7289DA',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    titleArea: {
        position: 'relative',
        fontSize: '24px',
        right: '25%',
        marginBottom: '20px',
    },
    topBar: {
        position: 'relative',
        width: '102.4%',
        height: '1px',
        backgroundColor: '#404040',
    },
    leftBar: {
        position: 'absolute',
        borderLeft: '1px solid #404040',
        right: '80%',
        top: '85px',
        height: '100vh',
        flexDirection: 'column',
        flex: 1,
    },
    greyBackground: {
        position: 'absolute',
        backgroundColor: '#000000',
        opacity: '0.3',
        left: '20%',
        width: '80%',
        height: '35%',
        top: '85px',
    },
    TextConnectTrigger: {
        position: 'absolute',
        fontSize: '20px',
        left: '25%',
        top: '20%',
        color: '#ffffff',
    },
    TextConnectAction: {
        position: 'absolute',
        fontSize: '20px',
        left: '59.5%',
        top: '20%',
        color: '#ffffff',
    },
    inputTrigger: {
        position: 'absolute',
        height: '40px',
        width: '20%',
        border: '1px solid gray',
        marginTop: '20px',
        marginBottom: '20px',
        paddingLeft: '10px',
        borderRadius: '5px',
        left: '25%',
        top: '20.7%',
    },

    inputAction: {
        position: 'absolute',
        height: '40px',
        width: '20%',
        border: '1px solid gray',
        marginBottom: '20px',
        paddingLeft: '10px',
        borderRadius: '5px',
        right: '20%',
        top: '22.9%',
    },
    suggestionBar: {
        position: 'relative',
        width: '20%',
        border: '1px solid gray',
        borderRadius: '5px',
        right: '54.8%',
        top: '29%',
        zIndex: '1',
    },
    suggestionBox: {
        position: 'absolute',
        width: '20%',
        border: '1px solid gray',
        borderRadius: '5px',
        backgroundColor: '#EEEEEE',
        right: '55%',
        top: '29%',
        zIndex: '1',
    },
    suggestionActionBox: {
        position: 'absolute',
        width: '20%',
        border: '1px solid gray',
        borderRadius: '5px',
        backgroundColor: '#EEEEEE',
        left: '60%',
        top: '29%',
        zIndex: '1',
    },
    suggestionChoice: {
        position: 'relative',
        padding: '5px',
        cursor: 'pointer',
        margin: '5px',
    },
    setZapButton: {
        position: 'absolute',
        backgroundColor: '#000000',
        color: '#ffffff',
        left: '50%',
        top: '23.3%',
        padding: '10px',
        borderRadius: '5px',
        cursor: 'pointer',
    },
    logoutButton: {
        position: 'absolute',
        backgroundColor: '#000000',
        color: '#ffffff',
        right: '2%',
        padding: '5px',
        borderRadius: '25px',
        cursor: 'pointer',
    },
    boxAppConnected: {
        position: 'absolute',
        width: '50%',
        top: '50%',
        left: '27.8%',
        border: '1px solid gray',
        borderRadius: '5px',
        backgroundColor: '#EEEEEE',
    },
    zapIsSet: {
        position: 'relative',
        marginTop: '20px',
        marginBottom: '20px',
        fontSize: '18px',
        textAlign: 'center',
        color: 'black',
        display: 'flex',
        left: '5%',
        alignItems: 'center',
    },
};
